version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '5000:5000'
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=162?_9482_stdswty1
      - POSTGRES_DB=libraryDB
    ports:
      - '5432:5432'
